//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebForm.WCFService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService", Namespace="http://tempuri.org/")]
    public partial class ServiceImplementation : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObterClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdicionarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExcluirClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarClientePorCPFOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceImplementation() {
            this.Url = global::WebForm.Properties.Settings.Default.WebForm_WCFService_ServiceImplementation;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObterClientesCompletedEventHandler ObterClientesCompleted;
        
        /// <remarks/>
        public event AdicionarClienteCompletedEventHandler AdicionarClienteCompleted;
        
        /// <remarks/>
        public event EditarClienteCompletedEventHandler EditarClienteCompleted;
        
        /// <remarks/>
        public event ExcluirClienteCompletedEventHandler ExcluirClienteCompleted;
        
        /// <remarks/>
        public event BuscarClientePorCPFCompletedEventHandler BuscarClientePorCPFCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/ObterClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFServiceHost.Models")]
        public Cliente[] ObterClientes() {
            object[] results = this.Invoke("ObterClientes", new object[0]);
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void ObterClientesAsync() {
            this.ObterClientesAsync(null);
        }
        
        /// <remarks/>
        public void ObterClientesAsync(object userState) {
            if ((this.ObterClientesOperationCompleted == null)) {
                this.ObterClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterClientesOperationCompleted);
            }
            this.InvokeAsync("ObterClientes", new object[0], this.ObterClientesOperationCompleted, userState);
        }
        
        private void OnObterClientesOperationCompleted(object arg) {
            if ((this.ObterClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterClientesCompleted(this, new ObterClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/AdicionarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AdicionarCliente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Cliente cliente) {
            this.Invoke("AdicionarCliente", new object[] {
                        cliente});
        }
        
        /// <remarks/>
        public void AdicionarClienteAsync(Cliente cliente) {
            this.AdicionarClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void AdicionarClienteAsync(Cliente cliente, object userState) {
            if ((this.AdicionarClienteOperationCompleted == null)) {
                this.AdicionarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdicionarClienteOperationCompleted);
            }
            this.InvokeAsync("AdicionarCliente", new object[] {
                        cliente}, this.AdicionarClienteOperationCompleted, userState);
        }
        
        private void OnAdicionarClienteOperationCompleted(object arg) {
            if ((this.AdicionarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdicionarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/EditarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EditarCliente(int clienteId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool clienteIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Cliente clienteAtualizado) {
            this.Invoke("EditarCliente", new object[] {
                        clienteId,
                        clienteIdSpecified,
                        clienteAtualizado});
        }
        
        /// <remarks/>
        public void EditarClienteAsync(int clienteId, bool clienteIdSpecified, Cliente clienteAtualizado) {
            this.EditarClienteAsync(clienteId, clienteIdSpecified, clienteAtualizado, null);
        }
        
        /// <remarks/>
        public void EditarClienteAsync(int clienteId, bool clienteIdSpecified, Cliente clienteAtualizado, object userState) {
            if ((this.EditarClienteOperationCompleted == null)) {
                this.EditarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarClienteOperationCompleted);
            }
            this.InvokeAsync("EditarCliente", new object[] {
                        clienteId,
                        clienteIdSpecified,
                        clienteAtualizado}, this.EditarClienteOperationCompleted, userState);
        }
        
        private void OnEditarClienteOperationCompleted(object arg) {
            if ((this.EditarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/ExcluirCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ExcluirCliente(int clienteId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool clienteIdSpecified) {
            this.Invoke("ExcluirCliente", new object[] {
                        clienteId,
                        clienteIdSpecified});
        }
        
        /// <remarks/>
        public void ExcluirClienteAsync(int clienteId, bool clienteIdSpecified) {
            this.ExcluirClienteAsync(clienteId, clienteIdSpecified, null);
        }
        
        /// <remarks/>
        public void ExcluirClienteAsync(int clienteId, bool clienteIdSpecified, object userState) {
            if ((this.ExcluirClienteOperationCompleted == null)) {
                this.ExcluirClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExcluirClienteOperationCompleted);
            }
            this.InvokeAsync("ExcluirCliente", new object[] {
                        clienteId,
                        clienteIdSpecified}, this.ExcluirClienteOperationCompleted, userState);
        }
        
        private void OnExcluirClienteOperationCompleted(object arg) {
            if ((this.ExcluirClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExcluirClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/BuscarClientePorCPF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Cliente BuscarClientePorCPF([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cpf) {
            object[] results = this.Invoke("BuscarClientePorCPF", new object[] {
                        cpf});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarClientePorCPFAsync(string cpf) {
            this.BuscarClientePorCPFAsync(cpf, null);
        }
        
        /// <remarks/>
        public void BuscarClientePorCPFAsync(string cpf, object userState) {
            if ((this.BuscarClientePorCPFOperationCompleted == null)) {
                this.BuscarClientePorCPFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarClientePorCPFOperationCompleted);
            }
            this.InvokeAsync("BuscarClientePorCPF", new object[] {
                        cpf}, this.BuscarClientePorCPFOperationCompleted, userState);
        }
        
        private void OnBuscarClientePorCPFOperationCompleted(object arg) {
            if ((this.BuscarClientePorCPFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarClientePorCPFCompleted(this, new BuscarClientePorCPFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFServiceHost.Models")]
    public partial class Cliente {
        
        private string cPFField;
        
        private int clienteIdField;
        
        private bool clienteIdFieldSpecified;
        
        private string dataExpedicaoField;
        
        private string dataNascimentoField;
        
        private EnderecoCliente enderecoField;
        
        private string estadoCivilField;
        
        private string nomeField;
        
        private string orgaoExpedicaoField;
        
        private string rgField;
        
        private string sexoField;
        
        private string uFExpedicaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        public int ClienteId {
            get {
                return this.clienteIdField;
            }
            set {
                this.clienteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClienteIdSpecified {
            get {
                return this.clienteIdFieldSpecified;
            }
            set {
                this.clienteIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataExpedicao {
            get {
                return this.dataExpedicaoField;
            }
            set {
                this.dataExpedicaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                this.dataNascimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EnderecoCliente Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EstadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                this.estadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrgaoExpedicao {
            get {
                return this.orgaoExpedicaoField;
            }
            set {
                this.orgaoExpedicaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RG {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UFExpedicao {
            get {
                return this.uFExpedicaoField;
            }
            set {
                this.uFExpedicaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFServiceHost.Models")]
    public partial class EnderecoCliente {
        
        private string bairroField;
        
        private string cEPField;
        
        private string cidadeField;
        
        private string complementoField;
        
        private int enderecoClienteIdField;
        
        private bool enderecoClienteIdFieldSpecified;
        
        private string logradouroField;
        
        private string numeroField;
        
        private string ufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public int EnderecoClienteId {
            get {
                return this.enderecoClienteIdField;
            }
            set {
                this.enderecoClienteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnderecoClienteIdSpecified {
            get {
                return this.enderecoClienteIdFieldSpecified;
            }
            set {
                this.enderecoClienteIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UF {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ObterClientesCompletedEventHandler(object sender, ObterClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AdicionarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void EditarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ExcluirClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void BuscarClientePorCPFCompletedEventHandler(object sender, BuscarClientePorCPFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarClientePorCPFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarClientePorCPFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591